# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(615, 622)

        # Temperature Control
        self.tempCmd = QtWidgets.QGroupBox(Dialog)
        self.tempCmd.setGeometry(QtCore.QRect(0, 10, 311, 91))
        self.tempCmd.setObjectName("tempCmd")
        self.tempCmdLayout = QtWidgets.QHBoxLayout(self.tempCmd)
        self.tempCmdLayout.setObjectName("tempCmdLayout")
        self.decreaseTempButton = QtWidgets.QPushButton(self.tempCmd)
        self.decreaseTempButton.setObjectName("decreaseTempButton")
        self.tempCmdLayout.addWidget(self.decreaseTempButton)
        self.tempValue = QtWidgets.QLineEdit(self.tempCmd)
        self.tempValue.setObjectName("tempValue")
        self.tempCmdLayout.addWidget(self.tempValue)
        self.increaseTempButton = QtWidgets.QPushButton(self.tempCmd)
        self.increaseTempButton.setObjectName("increaseTempButton")
        self.tempCmdLayout.addWidget(self.increaseTempButton)
        self.sendButton = QtWidgets.QPushButton(self.tempCmd)
        self.sendButton.setObjectName("sendButton")
        self.tempCmdLayout.addWidget(self.sendButton)
        

        # Temperature Real Time values
        self.tempDisplay = QtWidgets.QGroupBox(Dialog)
        self.tempDisplay.setGeometry(QtCore.QRect(0, 410, 281, 91))
        self.tempDisplay.setObjectName("tempDisplay")
        self.tempDisplayLayout = QtWidgets.QHBoxLayout(self.tempDisplay)
        self.tempDisplayLayout.setObjectName("tempDisplayLayout")
        self.label_temp = QtWidgets.QLabel(self.tempDisplay)
        self.label_temp.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 26pt \"MS Shell Dlg 2\";\n"
"")
        self.label_temp.setObjectName("labelTemperature")
        self.tempDisplayLayout.addWidget(self.label_temp)


        #Tension Real Time values demanded by the PI controller
        self.tensionDisplay = QtWidgets.QGroupBox(Dialog)
        self.tensionDisplay.setGeometry(QtCore.QRect(0, 510, 281, 91))
        self.tensionDisplay.setObjectName("tensionDisplay")
        self.tensionDisplayLayout = QtWidgets.QHBoxLayout(self.tensionDisplay)
        self.tensionDisplayLayout.setObjectName("tensionDisplayLayout")
        self.label_tension = QtWidgets.QLabel(self.tensionDisplay)
        self.label_tension.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 26pt \"MS Shell Dlg 2\";\n"
"")
        self.label_tension.setObjectName("labelTension")
        self.tensionDisplayLayout.addWidget(self.label_tension)


        # ON/OFF Connection Buttons
        self.conection = QtWidgets.QGroupBox(Dialog)
        self.conection.setGeometry(QtCore.QRect(350, 410, 217, 91))
        self.conection.setTitle("")
        self.conection.setObjectName("conection")
        self.connectionLayout = QtWidgets.QHBoxLayout(self.conection)
        self.connectionLayout.setObjectName("connectionLayout")
        self.offButton = QtWidgets.QPushButton(self.conection)
        self.offButton.setStyleSheet("background-color: rgb(231, 0, 0);")
        self.offButton.setObjectName("offButton")
        self.connectionLayout.addWidget(self.offButton)
        self.onButton = QtWidgets.QPushButton(self.conection)
        self.onButton.setStyleSheet("background-color: rgb(0, 195, 0);")
        self.onButton.setObjectName("onButton")
        self.connectionLayout.addWidget(self.onButton)
        self.graph = graph(Dialog)
        self.graph.setGeometry(QtCore.QRect(0, 100, 611, 301))
        self.graph.setObjectName("graph")


        # ON/OFF Fan Control
        self.fanCmd = QtWidgets.QGroupBox(Dialog)
        self.fanCmd.setGeometry(QtCore.QRect(350, 510, 217, 91))
        self.fanCmd.setTitle("")
        self.fanCmd.setObjectName("fanCmd")
        self.fanCmdLayout = QtWidgets.QHBoxLayout(self.fanCmd)
        self.fanCmdLayout.setObjectName("fanCmdLayout")
        self.offFanButton = QtWidgets.QPushButton(self.fanCmd)
        self.offFanButton.setStyleSheet("background-color: rgb(231, 0, 0);")
        self.offFanButton.setObjectName("offFanButton")
        self.fanCmdLayout.addWidget(self.offFanButton)
        self.onFanButton = QtWidgets.QPushButton(self.fanCmd)
        self.onFanButton.setStyleSheet("background-color: rgb(0, 195, 0);")
        self.onFanButton.setObjectName("onFanButton")
        self.fanCmdLayout.addWidget(self.onFanButton)
        self.graph = graph(Dialog)
        self.graph.setGeometry(QtCore.QRect(0, 100, 611, 301))
        self.graph.setObjectName("graph")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.tempCmd.setTitle(_translate("Dialog", "Temperature Command"))
        self.decreaseTempButton.setText(_translate("Dialog", "-"))
        f = self.tempValue.font()
        f.setPointSize(15)
        self.tempValue.setFont(f)
        self.tempToSend = 25
        self.tempValue.setText(str(self.tempToSend))
        self.tempValue.setAlignment(QtCore.Qt.AlignCenter)
        self.increaseTempButton.setText(_translate("Dialog", "+"))
        self.sendButton.setText("SEND")
        self.tempDisplay.setTitle(_translate("Dialog", "System real time temperature °C : "))
        self.label_temp.setText(_translate("Dialog", "0"))
        self.tensionDisplay.setTitle(_translate("Dialog", "Duty Cycle :"))
        self.label_tension.setText(_translate("Dialog", "0%"))
        self.conection.setTitle(_translate("Dialog", "System Connection"))
        self.offButton.setText(_translate("Dialog", "OFF"))
        self.onButton.setText(_translate("Dialog", "ON"))
        self.fanCmd.setTitle(_translate("Dialog", "Fan Control"))
        self.offFanButton.setText(_translate("Dialog", "OFF"))
        self.onFanButton.setText(_translate("Dialog", "ON"))
from graph import graph


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
